version: '1.0'
name: pipeline-20220525
displayName: pipeline-20220525
triggers:
  trigger: auto
  push:
    branches:
      prefix:
        - ''
stages:
  - name: stage-63c534e8
    displayName: 未命名
    strategy: naturally
    trigger: auto
    executor: []
    steps:
      - step: build@nodejs
        name: build_nodejs
        displayName: Nodejs 构建
        nodeVersion: 14.16.0
        commands:
          - npm install && node Build/index.js
        artifacts:
          - name: BUILD_ARTIFACT
            path:
              - ./dist
permissions:
  - role: admin
    members: []
